version: "2"
services:
  gatsby:
    build:
      context: ./
      dockerfile: ./.docker-config/gatsby/Dockerfile
    depends_on:
      - php
    ports:
      - 80:80
      - 81:9000
      - "9929:9929"
      - "9230:9230"
    volumes:
      - ./.docker-config/gatsby/docker-entry.js:/app/docker-entry.js
      - /app/node_modules
      - ./gatsby:/app
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
      - CHOKIDAR_USEPOLLING=1
      - ENABLE_GATSBY_REFRESH_ENDPOINT=true
      - CRAFTQL_URL=${CRAFTQL_URL}
      - CRAFTQL_API_KEY=${CRAFTQL_API_KEY}

  nginx:
    depends_on:
      - php
    volumes_from:
      - php
    build:
      context: .
      dockerfile: ./.docker-config/nginx/Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./.docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./craftcms/web:/var/www/html/web

  php:
    depends_on:
      - database
    build:
      context: .
      dockerfile: ./.docker-config/php/Dockerfile
    expose:
      - 9000
    volumes:
      - ./craftcms/config:/var/www/html/config
      - ./craftcms/backups:/var/www/html/backups
      - ./craftcms/templates:/var/www/html/templates
      - ./craftcms/modules:/var/www/html/modules
      - ./craftcms/web:/var/www/html/web
      - ./craftcms/craft:/var/www/html/craft
      - ./craftcms/composer.json:/var/www/html/composer.json
    environment:
      ENVIRONMENT: dev
      DB_DRIVER: mysql
      DB_SERVER: database
      DB_USER: project
      DB_PASSWORD: project
      DB_DATABASE: project
      DB_TABLE_PREFIX: craft_
      CRAFTCMS_EMAIL: ${CRAFTCMS_EMAIL}
      CRAFTCMS_USERNAME: ${CRAFTCMS_USERNAME}
      CRAFTCMS_PASSWORD: ${CRAFTCMS_PASSWORD}
      CRAFTCMS_SITENAME: ${CRAFTCMS_SITENAME}
      CRAFTCMS_LANGUAGE: en-GB
      SITE_URL: ${CRAFTCMS_SITE_URL}
      SECURITY_KEY: asdfasdfasdfasdfasdf

  database:
    image: mariadb:10.3
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8085:80
    environment:
      PMA_HOST: database

volumes:
  db-data:
    # couple of gotchas, run chown on all /var/www/html files when starting
    #
